/** Goal is to make a list of all the fish objects that will go on the DOM.
 * 1) Access the data for the fish 
 * 2) Call the function that turns the fish into HTML
 * 3) Run another funcion that turns the fish LIST into HTML
 * 3) Tell the computer where the newly generated HTML component should appear on the DOM
 * 3) Export the newly created fish list so it can be used by other components
 */ 

 // To access the data, we will import the function getBunchOfFish

import {getBunchOfFish} from "./showMeThoseFish.js"
            // The function "getBunchOfFish" passes in the Array, "bunchOfFish" and returns a copy of the array


import {makeFish} from "./makeFish.js"
            // The function "makeFish" passes in "thisFish" to generate the HTML representation of a "fish--card"


// Now this doc has the ability to access the above functions. 

//  Create a function that combines all digitalFish into a list
export const fishList = () => {

    // We want this function to actually change the content of an HTML element on the DOM.
    /** We will use the querySelector() method, passing in the CSS Selector ".content--left"
     * to specify which HTML element we want to change/replace with this js.
     * We will assign a variable which will represent the HTML element which is returned.
     */
     
    const fishListLocation = document.querySelector(".content--left")
            // NOTE: We have deleted the hard coded HTML from the ".content--left" section of the index.html.
            // Therefore, this variable is essentially an "empty" variable to which we can ADD content.

    // Create a VARIABLE which contains "bunchOfFish", generated by the function "getABunchOfFish"
    const gotFish = getABunchOfFish()

    // Create an EMPTY variable which will hold the HTML output for each "fish--card" - essentially a digitalFish
    let digitalFish = ""

    // Iterate over the array contained within gotFish 
    for (const eachFish of gotFish) {
            // every time the loop runs, we want to ADD another digitalFish
        digitalFish += makeFish(eachFish)
            // to create the digitalFish, we run the function makeFish and pass in the argument eachFish within the array gotFish
    }

    // We want to actually CHANGE the Property of the empty HTML element we have selected in the fishList function

    fishListLocation.innerHTML += `
        <article class="fish-list">
            ${digitalFish}
        </article>
    `

}